                                                                            #WELCOME#
                                                        #Computer Science Project Of Class :- XI , 2019-20#
                                                    #NAME:- Vivek Kumar Maurya ; CLASS:- XI-C : ROLL NO.: 00000
while True:
    print("  ")
    print("  ")
    print("                                                                   NAVJEEVAN HOSPITAL $ TRAUMA CENTRE ")
    print("                                       ---*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*---")
    print("                                                      Address:-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    print("                                       ---*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*---")
    print("                                                                   Contact No. :- xxxxxxxxx  ")
    print("                                       ---*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*---")
    print("(   Sunday Closed  )")
    print("-----------------------")
    print("  ")
    print(" ~~> HOME PAGE :-")
    print("     -----------------------")
    print("  ")
    print(" 1.  About the Hospital :")
    print(" 2.  Hospital Facilities : ")
    print(" 3.  Patient Records:")
    print(" 4.  Registration :")
    print(" 5.  Patient Enquiry : ")
    print(" 6.  Medicine Store :")
    print(" 7.  Fee Counter :")
    print(" 8.  Relieving Card :")
    print(" 9.  Exit :")
    print("  ")
    a=int(input("Enter Your Choice From Above :- "))
    print("  ")
    if a==1:
        print("  ")
        print("  You Are In ' ABOUT THE HOSPITAL ' Page ---")
        print("---------------*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-------------")
        print("  ") 
        print("The multifarious medical needs of the Campus population consisting of Students, Staff members and members of their families are met by the Institute Hospital. The Hospital is headed by the Head (Hospital Services) with a team of full time Medical Officers, Visiting Specialists and Para Medical staff. The Director has also constituted a Hospital Advisory Committee with a Chairman nominated by him and members drawn from hospital and other recognized bodies of the Institute including student representatives, with the Head (Hospital Services) as the Member Secretary of the Committee. This Committee formulates various policies for providing medical facilities to the Campus population.")
        print("The Navjeevan Hospital has facilities for OPD treatment in almost all branches of medicine with facilities for pathological/radiological investigations and in addition has a dental and physiotherapy wing. It also has adequate facilities, both infrastructure and expertise wise for all types of minor operations. Facilities for both surgical and medical cases exist with 12 beds.")
    if a==2:
        print("  ") 
        print("   You Are In ' HOSPITAL FACILITIES ' Page ----")
        print("---------------*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-------------")
        print("  ")
        print("1.24x7 Emergency Services:")
        print("2.Cantein Service:")
        print("3.Vehicle Parking Services:")
        print("4.Room Service For Patience:")
        print("5.Medicine Shop Available:")
        print("6. Other Facilities:")
        b=int(input("Choose Required Service:-"))
        if b==1:
              print("ffFEFE")
        if b==2:
              print("-:You Are Choosen CANTEIN SERVICES Option :-")
              print("-->Menu :- ")
              print("1.Veg:")
              print("2.Nonveg:")
              print("3.Chinese:")
              print("4.Other items:")
              c=int(input("Choose From Our Menu List:"))
              if c==1:
                    print(" Dishes                                            Prices(Rs.)")
                    print("i.Dal (1 Plate)                                      50")
                    print("ii. Rice (1 Plate)                                   30")
                    print("iii.Matar Paneer (1 Plate)                 100")
                    print("iv.Nan (3 Piece)                                  30")
                    print("v.Mix Veg(1 Plate)                              80")
              if c==2:
                    print(" Dishes                                            Prices(Rs.)")
                    print("i.Chicken(1 Plate)                               120")
                    print("ii.Egg Cury (1 Plate                               80")
                    print("iii.Matan (1 Plate)                                    125")
                    print("iii.Fish cury(1 Plate)                               110")
              if c==3:
                    print(" Dishes                                            Prices(Rs.)")
                    print("Chawmean ( 1 Plate)                       25")
                    print("Pasta(1 Plate)                                   23")
                    print(" Momos(1 Plate)                             30")
              if c==4:
                    print(" Dishes                                            Prices(Rs.)")
                    print("Tea(1 cup)                                             10")
                    print("Coffee (1 cup)                                       15")
                    print(" Samosa( 2 piece)                                12")
                    print("Bread $ Bhajiya( 1 Plate)                    20")
        if b==3:
                    t=input("Name:-")
                    rt=input("Mob. No. :-")
                    uit=input("Vehicle No. :-")
                    ut=input("Time Of Entry:-")
                    er=input("Time of Exit:-")
                    er=input("Amount :-")
        if b==4:
                    print ("-:You Are Choosen ROOM SERVICES FOR PATIENCE Option:-")
                    print("I. 24 x 7 Room services for patience with 2 bed , 1 table with drawer and locker,light, fan or A.C.,T.V., separate bathroom etc .")
                    print("II. Only 1 person stayed in night with patience.")
        if b==5:
                    print ("-:You Are Choosen MEDICINE SHOP AVAILABLE Option:-")
                    print("For  Medicine Shop Query, Please Open link from the home page option")
        if b==6:
            print("            List of facilities available at Navjeevan Hospital")
            print("  -----------------------------------------------------------------------")
            print("  ")
            print("•   OPD (Allopathy & Homeopathy):")
            print("Patients are registered at the reception and are seen on first come, first serve basis, however out of turn consultation may be provided in case of emergency and senior citizen. Patients have the right to consult any doctor. In OPD, clinical consultation is provided to patients which includes history taking, clinical examination, diagnosis and providing prescription to patients besides advising laboratory tests in some cases. OPD has a waiting hall with chairs, a TV, public utilities like drinking water and toilets. Sub waiting areas are available in front of individual consultation rooms. Wheel chairs, trolleys and attendants are there to help very sick patients.")
            print("  ")
            print("•   Dental facility:")
            print("An experienced Dental surgeon provides procedures like Dental Extractions, RCT, Scaling /Cleaning, Fillings, Local curettage.")
            print("  ")
            print("•   Ward/ Indoor facility:")
            print("Ward facilities for observation and management of medical problem like typhoid, acute gastroenteritis, COPD, bronchial asthma, malaria, viral fever, pneumonias etc. There are 3 wards, one special room and one well equipped emergency.")
            print("  ")
            print("•   Minor OT/ Dressing Room:")
            print("Provides services for minor surgical procedure like dressing of lacerated wound, suturing of minor lacerations & resuturing.")
            print("  ")
            print("•   Physiotherapy:")
            print("Range of physiotherapy services to assist the patients to recover from wide range of musculoskeletal pain-ful disorders. Available modalities are MWD, SWD, U/S, TENS, IFC laser therapy traction unit, magnolia.")
            print("  ")
            print("•   Laboratory services:")
            print("Trained laboratory staff are providing best services which includes painless blood withdrawal Services of one NABL accredited laboratory are also available for carrying out specialised tests, they collect sample from 8 AM to 12 noon. In IIT Hospital.")
            print("Sample collection time for IIT laboratory is 8 am to 10.30 am and upto 11:00 am for student while emergency tests like Blood sugar, platelet count & blood grouping done in emergent cases throughout OPD hours.")
            print("  ")
            print("•   ECG Services:")
            print("24hours ECG services including machine report, done by trained staff.")
            print("  ")
            print("•   Pharmacy:")
            print("Free reliable quality medicines are available to beneficiaries on doctor prescription during OPD hours. Medicines not available are provided by S.O. signed by prescribing Doctor and Head and collected from on campus chemist shop.")
            print("  ")
            print("•   Radiology/X-ray facility:")
            print("X-Ray pleophos-D, 300 MA Siemens available, X-rays done on all working days during OPD hour. Sonoline G-50 U/S machine, Siemens. Ultrasounds are done once a week.")
            print("  ")
            print("•   Ambulance Services:")
            print("24 hours patient transport vehicle available. Patients are transported from home (on campus) to IIT hospital and patients referred by emergency duty doctor to empanelled hospital for specialized care.")
            print("  ")
    if a==3:
        print("  ")
        print("  You Are In ' PATIENT RECORDS ' Page ----")
        print(" -----------*-*-*-*-*-*-*-*-*-*-*-*-*-------------")
        print("  ")
        a=int(input("No. Of  Patient:-"))
        b=0
        while b<a:
            g=input("Patient Name:-")
            e=input("       * Age :- ")
            d=input("      * D.O.B. :-")
            e=input("      * Gender :-")
            f=input("      * Mobile No. :-")
            g=input("     * Address :-")
            gh=input("    *Disease Name :- ")
            print("  ")
            o=print("Patient Name -",g,"Age -",e,"D.O.B -.",d,"Gender -",e,"Mobile no. -",f,"Address -",g,"Disease -",gh)
            b=b+1
    if a==4:
        print("  ")
        print("       You Are In ' REGISTRATION ' Page ---")
        print("---------------*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-------------") 
        print("  ")
        b=input("      * Patient name:- ")
        c=input("       * Age :- ")
        d=input("      * D.O.B. :-")
        e=input("      * Gender :-")
        hj=input("     * Height :-")
        kl=input("     * Weight :- ")
        f=input("      * Mobile No. :-")
        g=input("     * Address :-")
        gh=input("    *Disease Name :- ")
        print("  ")
        print("                      -:Doctors Time Schedule :- ")
        print("                ------------------------------------------")
        print("  ")
        print("                      -:Doctors Time Schedule :- ")
        print("                ------------------------------------------")
        print("       Doctor Name                                          Timing ")
        print("  -----------------------                                -----------------")
        print("Dr. Renu Misurya	                    8:00 AM to 2:00 PM")		
        print("Dr. Malini Kaul 	                    12:00 PM to 8:00 PM")	
        print("Dr. Rajesh	                       9:00 AM to 2:00 PM and 3:00 PM to 6:00 PM")		
        print("Dr. Shalini Singh	    9:00 AM to 2:00 PM and 3:00 PM to 6:00 PM")	
        print("Dr. Abhishek Gupta	    9:00 AM to 2:00 PM and 3:00 PM to 6:00 PM")	
        print("Dr. Zeenat 	                                       8:00 AM to 2:00 PM")		
        print("Dr. Mahesh Sagar	    9:00 AM to 2:00 PM and 3:00 PM to 6:00 PM")	
        print("Dr. Lily Khosa	    9:00 AM to 2:00 PM and 3:00 PM to 6:00 PM")	
        print("Dr. Anila Khosla	    9:00 AM to 2:00 PM and 3:00 PM to 6:00 PM")	
        print("Dr. Ashfaque Hussain	    9:00 AM to 2:00 PM and 3:00 PM to 6:00 PM")	
        print("Dr. Ajay Kumar Jain	                    8:00 AM to 8:00 PM ")	
        print("Dr. Yasmeen Raunaq	                    2:00 PM to 8:00 PM")	
        print("Dr. Ajay Kumar Jain	                    8:00 AM to 2:00 PM")
        ty=input("Reff. By Doctor :-")
    if a==5:
        print("  ")
        print("     You Are In ' PATIENT ENQUIRY ' Page ---")
        print("---------------*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-------------")
        print("  ")
        h=input("      * Patient Name :-")
        i=input("       * Address :-")
        j=input("       * Room No.:-")
        k=input("")
    if a==6:
        print("  ")
        print("      You Are In ' MEDICINE STORE ' Page ---")
        print("---------------*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-------------")
        print("  ") 
        print(" Medicine Name             Price(Rs.)                  D.O.M            D.O.E   ")
        print("~~~~~~~~~~~~~       ~~~~~~~~             ~~~~~~~     ~~~~~~~")
        print("Combiflam                         50.05                    12-01-2019     12-04-2021")
        print("Norflox-TZ                         55.15                     01-12-2018     15-06-2020")
        print("Avil-500                              25.34                    26-09-2019     23-05-2022  ")
        print("Vicks Action-500              85.56                     25-11-2018      24-07-2021  ")
        print(" Paracitamol                      75.01                      23-04-2019     25-02-2022")
        print("ZO-200                               60.12                     29-01-2019       05-03-2022")
        print("Belargan                             85.76                      29-12-2018      11-02-2022  ")
        print(" Lyrica                                 95.89                      23-07-2019      28-04-2022 ")
        print(" Viagra                                 85.99                      07-02-2019      31-12-2022 ")
        print("Codiene                                55.53                      16-01-2019      29-11-2021  ")
        print("  ")
        y=input("Enter name :-")
        z=int(input("no. of medicine required:-"))
        b=0
        while b<z:
                o=int(input("Price of medicine :-"))
                b=b+1
    if a==7:
        print("  ") 
        print("       You Are In ' FEES COUNTER ' Page ---")
        print("---------------*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-------------")
        print("  ")  
        m=input("                * Patient Name:- ")
        n=int(input("           * Entry Fee :- "))
        o=int(input("           * Doctor's Fee:-"))
        p=int(input("           * Checkup Fee:-"))
        q=int(input("           * Operation Fee:-"))
        r=int(input("            * Medicine Fee :-"))
        s=int(input("            * Exit Fee :-"))
        i=int(input("             * Per Day Fee:-"))
        e=int(input("            * Total No. Of Days :-"))
        t=(n+o+p+q+r+s+(i*e))
        print("Total Fees Of Patient :-",t)
    if a==8:
        print("  ")
        print("     You Are In ' RELIEVING CARD ' Page ---")
        print("---------------*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-------------")
        print("  ")
        u=input("          * Patient Name :-")
        v=input("          * Age:- ")
        w=input("         * Date Of Entry:-")
        x=input("          * Date Of  Exit:-")
        y=input("          * Total Fees Of Patiente:-")
        tt=input("          * Mobile No. :-")
        rt=input("          * Address :-")
    if a==9:
        print("  ") 
        print("       You Are In ' EXIT ' Page")
        print("---------------*-*-*-*-*-*-*-*-*-------------")
        print("  ")
        print("  ")
        print ("                                                                                         --|--Thanks For Visit--|--")
        print("  ") 
        print("--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--*--")
            

          
